name: Monkey's Space
description: 记录一些琐事
meta_description: "网络日志，记录一些琐事"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /blog/
domain_name: 'https://github.com/chenxiaozhong'

# Details for the RSS feed generator
url:            'blog url'
author:         'Monkey'
